### ISSUE TITLE
As a client of the client, I'd like to use the new "latest/all" API calls

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/pds-api-client#12]
[This pull request](https://github.com/NASA-PDS/registry-api-service/pull/67) added features to the registry API that supported getting the latest versus all products when dealing with bundles that contain LID-only as opposed to full LIDVID references.

However the Python API client has not been updated to support these new APIs. It should also be updated.

**Comment by jordanpadams** [comment]
@nutjob4life it was pushing to [this branch instead](https://github.com/NASA-PDS/pds-api-client/tree/swaggerhub-pds_federated_api-main) 🤦 .

just pushed to main. should go to test pypi soon. we can then tag an operational release as soon as you have been able to test.

**Comment by tloubrieu-jpl** [comment]
I see how to publish that on pypi following instructions on https://github.com/NASA-PDS/pds-api-client/blob/main/HOW-TO-GENERATE.md

To retrofit it to github action would be a task for later.

**Comment by nutjob4life** [comment]
@jordanpadams okay, I thought you had to manually pull the `swagger.json` file somehow.

That's good because the SwaggerHub links (on [this page](https://github.com/NASA-PDS/registry-api-service), [this page](https://github.com/NASA-PDS/pds-api), and [this page](https://github.com/NASA-PDS/pds-api-javalib)) all go nowhere.

@tloubrieu-jpl I will follow the instructions and give it a try!

**Comment by nutjob4life** [comment]
Ooof okay I called it 0.6.2 on testpypi but there are some big API changes: the `models` module can no longer be implicitly imported by a parental `import pds.api_client` and the various entity classes in there have been renamed (e.g., `Product` → `Pds4Product`), also the `bundle_by_lidvid` method no longer returns a `Product` object but a plain `dict`, member access is by name and not by field, etc.

Upshot is: **let's call it 0.7.0** when it goes to the real PyPI.
