### ISSUE TITLE
Import failure for pds.api_client.CollectionsApi using PIP package 0.8.0

### ISSUE THREAD

**Issue by cpiker** [NASA-PDS/pds-api-client#17]
## 🐛 Describe the bug
Example code in [quickstart/index.rst](https://github.com/NASA-PDS/pds-api-client/blob/main/docs/source/quickstart/index.rst) doesn't work for version 0.8.0.

## 📜 To Reproduce
Steps to reproduce the behavior

1. Install pip package, start python 3.8 on Linux ubuntu 20
```bash
$ pip3 install pds.api-client
$ python3.8
```
2. Import the CollectionsApi 
```python
>>> from pds.api_client import CollectionsApi
```
3. Get error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'CollectionsApi' from 'pds.api_client' ($HOME/.local/lib/python3.8/site-packages/pds/api_client/__init__.py)
```
where $HOME represents user home directory.

## 🕵️ Expected behavior
An import with no traceback

## 📚 Version of Software Used
0.8.0 from PIP install

## 🖥 System Info
 - OS: Linux, ubuntu 20, python3.8
---

**Comment by jordanpadams** [comment]
@tloubrieu-jpl can we track down the issue here ASAP?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl this was a user identified critical bug that has now been open for 2 weeks. can we please look at this or get someone to look at this ASAP?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams sorry I missed that. I will do something for that today.

**Comment by tloubrieu-jpl** [comment]
@cpiker @jordanpadams 

I have updated the documentation on https://nasa-pds.github.io/pds-api-client/quickstart/index.html

I will close the ticket with that. You can re-open it or open a new one if something else goes wrong.

Thanks

**Comment by jordanpadams** [comment]
closed per 295f0a5792b7c5b892bbef43feb393c27ae8d23b

**Comment by cpiker** [comment]
Thanks for updating the docs, I was able to get a bit further.  Though the example cod above gives a 500 Internal Server Error, I presume that's just a temporary outage.

**Comment by tloubrieu-jpl** [comment]
Thanks @cpiker , let's create new ticket for this issue
