### ISSUE TITLE
Links to client API details are broken on GitHub site

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api-client#18]
## 🐛 Describe the bug

From https://nasa-pds.github.io/pds-api-client/quickstart/index.html#create-an-api-connection, links to CollectionAPI, BundleAPI, and ProductAPI are all broken.

**Comment by tloubrieu-jpl** [comment]
The links have been repaired and a new version of the doc is published https://nasa-pds.github.io/pds-api-client/quickstart/index.html#request-one-end-point

**Comment by jordanpadams** [comment]
closed per 2ee3bebec5e7131be74c04c7a6c660229c7d109e
