### ISSUE TITLE
PDS API Client 1.0.0 cannot communicate with pds-gamma

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/pds-api-client#2]
## 🐛 Describe the bug

The PDS API Client can't talk to `pds-gamma` again (as of 2021-03-28Z02:38:05).

## 📜 To Reproduce

```console
$ python3 --version
Python 3.9.2
$ python3 -m venv venv
$ cd venv
$ bin/pip install --quiet pds.api_client
$ curl --silent --location --remote-name https://raw.githubusercontent.com/NASA-PDS/pds-api-client/master/client-demo.py
$ bin/python3 client-demo.py
Traceback (most recent call last):
…
ValueError: Invalid value for `ref`, must not be `None`
```

## 🕵️ Expected behavior

Pretty-printing of the API response.

## 📚 Version of Software Used

Output from `validate -V`:

```console
$ validate -V
validate: Command not found.
```

## 🩺 Test Data / Additional context

No test data applicable save for `client-demo.py`. For additional context: the behavior of http://pds-gamma.jpl.nasa.gov/api/ seems to come and go; it sure makes developing a solution for https://github.com/NASA-PDS/pds-deep-archive/issues/7 tricky! 

##  🏞Screenshots

![Screen Shot 2021-03-28 at 9 37 55 PM](https://user-images.githubusercontent.com/814813/112780183-eec82200-900d-11eb-92f0-7daafce8b529.png)

## 🖥 Desktop
- OS: macOS 11.2.3 (20D91)
- Browser: Safari 14.0.3 (16610.4.3.1.7)
- Version pds.api-client 1.0.0

---

**Applicable requirements**
 :unicorn:

**Comment by jordanpadams** [comment]
@nutjob4life is this still not working? looks like i can click a couple things successfully here: https://pds-gamma.jpl.nasa.gov/api/swagger-ui.html ?

**Comment by nutjob4life** [comment]
@jordanpadams yes, through-the-web is working. But the [client API](https://pypi.org/project/pds.api-client/) is not 😢

I'd prefer if the Deep Archive could use the client API!

**Comment by jordanpadams** [comment]
@nutjob4life agreed.

@tloubrieu-jpl can you help out here? you are using the client for your Jupyter work, so maybe you have some updated code and/or there is some config issue here?

**Comment by tloubrieu-jpl** [comment]
@nutjob4life you need to upgrade the client, `pip install pds-api-client==0.4.0`

Note that version 1.0.0 has been release by mistake... So this is not the latest. While I am writing that, I am seeing this is horrible. Next update should be 1.1 (unless there is a way to delete a pypi package version).

**Comment by al-niessner** [comment]
You can delete it but cannot reuse it. In other words, delete 1.0.0 then
when you want to make a 1.0.0 you will have to make it 1.0.1 or 1.1.0 or
1.0 but pypi will remember you had 1.0.0 and prevent you from using it
again.

**Comment by nutjob4life** [comment]
Wait…1.0.0 is _not_ the latest? 😑 You know how long I've been trying to develop against it @tloubrieu-jpl @al-niessner? 😝

I do recommend pushing out a 1.0.1 to PyPI ASAP, even if 1.0.1 == 0.4.0. "Upgrading" from 1.0.0 → 0.4.0 feels wrong 😅

💁‍♀️ You cannot remove releases from PyPI but you can mark one as "yanked". That will tell `setuptools`, `pip`, `buildout`, etc., that the release shouldn't be used. See the screenshot:
<img width="827" alt="Screen Shot 2021-03-29 at 4 10 27 PM" src="https://user-images.githubusercontent.com/814813/112900798-8f1f5480-90a9-11eb-99e4-863fdb5d27bc.png">

**Comment by jordanpadams** [comment]
@nutjob4life would you mind "yanking" the 1.0.0?

**Comment by tloubrieu-jpl** [comment]
@nutjob4life @jordanpadams I've just done it.
I will add you as owner/manager of the package.

**Comment by nutjob4life** [comment]
You know guys, we should double-check all our PyPI packages and make sure we add each other (and a common PDS EN account) as an additional owner on the off chance one of us suffers a fatal "kernel panic".

And to keep it from happening in the future…perhaps a periodic GitHub Action that compares Python-based repositories here with their corresponding packages on PyPI and alerts when there's sole owners?

**Comment by jordanpadams** [comment]
@nutjob4life 100% agree and we def need to do better here. Sorry for the headache. An improvement opportunity for sure. I will create a ticket to address this as well. As our team and dependencies grow, we def need to take our devops up a notch.

**Comment by nutjob4life** [comment]
@jordanpadams sign me up to help with that! And no apologies necessary.

**Comment by jordanpadams** [comment]
@nutjob4life will be adding this to our B12.0 release plan: NASA-PDS/pdsen-operations#90

**Comment by jordanpadams** [comment]
also @nutjob4life have you had a chance to test with the new package?

**Comment by nutjob4life** [comment]
@jordanpadams not yet, I changed gears to do cancer work. Wish me luck as I try to integrate it in the next 36 hours 😅

**Comment by nutjob4life** [comment]
Confirmed it works!
