### ISSUE TITLE
Update pds-api-client to be compliant with API v1.1

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/pds-api-client#22]
## 💡 Description
The python client needs to be updated for B13.0 to be compliant with v1.1 of the API.

**Comment by jimmie** [comment]
Need to determine which client code generation tool to utilize. Recent versions of OpenAPITools' generator creates very cludgy and unintuitive code and requires modification of the pds.api_client package name. Another initially promising tool is openapi-python-client. Neither provides support for deserialization of response bodies in any form other than JSON although the former supports returning non-deserialized results that can be in any content type supported by the registry service.

**Comment by jimmie** [comment]
Adding @tloubrieu-jpl as co-assignee to see if he can get his fork of the OpenAPITool to build and run.

**Comment by jimmie** [comment]
The command line to generate the code using the docker image of openapitools is:

Download the image:
`docker pull openapitools/openapi-generator-cli`

Then to run it (this assumes the swagger.json has been run through the preprocessor):
`docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i /local/preprocessed-swagger.json -g python -o /local/out/python --package-name pds_api_client --additional-properties=packageVersion=1.1.0`

**Comment by jimmie** [comment]
To use the openapi-python-client:

Install the tool (recommended to use a distinct conda or virtual environment):
`pip install openapi-python-client`

Then to run it (again, using the preprocessed swagger json):
`openapi-python-client generate --path ./preprocessed-swagger.json`

**Comment by jimmie** [comment]
Example based on the code generated by openapi-generator-cli. Note that 'pds.api_client' had to be changed to 'pds_api_client' - otherwise the generator creates (illegal) imports w/ slashes (i.e. 'pds/api_client').

```
from pds_api_client import configuration, api_client
from pds_api_client.paths.products import get as products_get
_configuration = configuration.Configuration()
_configuration.host='http://localhost:8080'
client = api_client.ApiClient(_configuration)
api = products_get.ApiForget(client)
api.get(accept_content_types = ('application/json',))

response = api.get(accept_content_types = ('application/json',), skip_deserialization = True)
print(response.response.info())
print(response.response.data)

from frozendict import frozendict
from pds_api_client.paths.products_identifier import get as products_id_get
api = products_id_get.SelectByLidvid(client)
response_json = api.select_by_lidvid(path_params = frozendict({'identifier' : 'urn:nasa:pds:mars2020.spice'}), accept_content_types = ('application/json',))
print(response_json)

api = products_id_get.ApiForget(client)
response_json = api.get(path_params = frozendict({'identifier' : 'urn:nasa:pds:mars2020.spice'}), accept_content_types = ('application/json',))
print(response_json)
```

**Comment by tloubrieu-jpl** [comment]
@jimmie the first issue I was bumping into is the the unresolved json that I am exprting from swaggerhub is actually resolved which make the `component` definition distributed into the `path` definition, whereas I think the openapi generator requires to have the components which will be defined in the api data model.

I will look further into it.

**Comment by tloubrieu-jpl** [comment]
I found this bug https://github.com/OpenAPITools/openapi-generator/pull/14015 referenced in the openapi-generator project which apparently is solved and should enable us to use nested package name (pds.api-client). I will try that now.

**Comment by tloubrieu-jpl** [comment]
That works

**Comment by tloubrieu-jpl** [comment]
So far, it sounds like openapi-generator can work in an 'ok' way, but the API generated is not backward compliant.

I am now trying to regenerate the API with openapi-generator version 5.4.

**Comment by tloubrieu-jpl** [comment]
Next steps:
- find and read documentation on how to use the generated python classes to make sure it we guide users properly
- finalize tests migration with upgrade api client
- develop tests with the new classes/products style

**Comment by tloubrieu-jpl** [comment]
See PR https://github.com/NASA-PDS/pds-api-client/pull/23
