### ISSUE TITLE
product_properties_list() returns None

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api-client#29]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When I did request  action product_properties_list(), I noticed the response was None, see this piece of code:

"""

from __future__ import print_function
from pds.api_client.rest import ApiException
from pds.api_client import Configuration
from pds.api_client import ApiClient
from pds.api_client.api.all_products_api import AllProductsApi
from pprint import pprint

# create an instance of the API class
configuration = Configuration()
#configuration.host = 'https://pds.nasa.gov/api/search/1'
#configuration.host = 'https://pds.nasa.gov/api/search-en-gamma/1'
configuration.host = 'http://localhost:8080'
api_client = ApiClient(configuration)

all_products = AllProductsApi(api_client)

try:
    # see ref doc on
    api_response = all_products.product_properties_list()
    pprint(api_response)

except ApiException as e:
    print("Exception when calling CollectionsApi->get_collection: %s\n" % e)

"""

### 🕵️ Expected behavior

I expected to get the list of available properties

### 📜 To Reproduce

1.
2.
3.
...

### 🖥 Environment Info

- 1.4.0

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

This is likely due to the fact that the response in the swagger specification does not specify an object type.

**Comment by gxtchen** [comment]
@tloubrieu-jpl can you allow me to add the i&t done tag to this ticket?
