### ISSUE TITLE
Client 1.5.0 doesn't seem to support "latest" or "all" functions

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/pds-api-client#35]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

Several of the [endpoints documented for the PDS API](https://pds.nasa.gov/api/search-en-gamma/1/swagger-ui/index.html) have features where you can get the "latest" or "all" products, such as `/products/{identifier}/latest` and `/products/{identifier}/all` to name a few. However, the Python API client doesn't expose this function as far as I can tell.

### 🕵️ Expected behavior

I thought the Python API client would have the latest/all functions. I can't find them.

### 🖥 Environment Info

pds.api-client 1.5.0

### 📚 Version of Software Used

pds.api-client 1.5.0

### 🦄 Related requirements

🦄 #xyz

**Comment by tloubrieu-jpl** [comment]
Hi @nutjob4life ,

The `api-client` can request `all` or `latest` as follow:

```
api_response = product_references.product_members_vers(
    'urn:nasa:pds:mars2020_sherloc::1.0',
    versions='latest',
    limit=20,
    fields=['ops:Label_File_Info.ops:file_ref']
)
```

But changing from `all` to `latest` does not have an effect. I believe it comes from the API itself, I discussed that briefly with @jordanpadams last week and will create some tickets with very low priority related to that.

**Comment by nutjob4life** [comment]
@tloubrieu-jpl ah, the `versions` parameter. Thank you! 👍  

I think we could use some documentation for this, as it wasn't obvious to me 😁
