### ISSUE TITLE
As a developer, I want to be able to create other Python packages utilizing the pds namespace

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api-client#7]
## Motivation
...so that I can use the `pds.api_client` as a dependency, and not worrying about it breaking the software.

## Additional Details

Per development done in https://github.com/NASA-PDS/pds-deep-archive/pull/114, came across issue when trying to us the `pds.api_client` in another package utilizing the `pds` namespace.

Per convo on slack with @nutjob4life :
> This came up because there seems to be a random run-time resolution to packages. If a user of pds.api_client, say pds.aipgen gets picked up first, then it's fine because that package claims pds as a "namespace package". Other pds.whatever get found fine.
>
> However, if pds.api_client gets picked up first, its  pds/__init__.py doesn't delcare pds as a namespace. So Python sets the __path__ resolution for pds-based lookups to its location (typically lib/python/site-packages/pds).  So when my code tries to import pds.aipgen.whatever, it looks in lib/python/site-package/pds/aipgen and can't find it.

## Acceptance Criteria
**Given** the pds.api_client as a dependency for other Python packages which may or may not use the top-level `pds` module and/or namespace package
**When I run** programs from such Python packages
**Then I expect** them to import from `pds.api_client` while also not having their own `pds.*` modules shadowed by it.

The [small test repo](https://github.com/nutjob4life/pds) contains three small Python packages that use `pds.api_client` as a dependency. All three should succeed. (As of this writing, one one succeeds.)

## Engineering Details

Per slack convo, some ideas for making this happen:
* Add post-commit to repo where we declare `pds` as a namespace in `pds/__init__.py`
* Same as above but utilizing a Github action

**Comment by jordanpadams** [comment]
@nutjob4life please update the success criteria or details above if I missed something

**Comment by nutjob4life** [comment]
Hi @jordanpadams because this one is _tricky_, I made [a smaller test repo](https://github.com/nutjob4life/pds) that demonstrates what's going on.

I'll also update the acceptance criteria to reflect this.

**Comment by tloubrieu-jpl** [comment]
I believe this is fixed with this commit https://github.com/NASA-PDS/pds-api-client/commit/5fb4e0dbc65a5a79180051c29d01177e68f8c7d9

I was able to use updart as namespace `pds.updart` and import `pds.api_client`.

**Comment by tloubrieu-jpl** [comment]
Hi @nutjob4life, I ma pinging you in case you want to test that and rename the namespace of `deep-archive`.

**Comment by tloubrieu-jpl** [comment]
Oh but you are not using the `pds.api-client` anymore in `deep-archive`, nevermind...

**Comment by nutjob4life** [comment]
Hi @tloubrieu-jpl! Thanks for taking a look at this. Right, the Deep Archive uses the URLs directly. 

But good to have this fixed anyway! Thanks!

By the way, the management of namespace packages has changed _drastically_ in Python-land since this ticket was first opened in 2021. We might want to take a closer look at the latest state-of-practice of namespaces and modernize our Python template repository.

**Comment by tloubrieu-jpl** [comment]
Thanks @nutjob4life , I think I am using native namespace package, the fix was not done long ago.

**Comment by jordanpadams** [comment]
@nutjob4life to review and close and/or create new ticket on template repo to make appropriate changes

**Comment by nutjob4life** [comment]
@tloubrieu-jpl I reviewed 5fb4e0dbc65a5a79180051c29d01177e68f8c7d9 and I'm fine with it, thanks.

**Comment by nutjob4life** [comment]
@tloubrieu-jpl I reviewed 5fb4e0dbc65a5a79180051c29d01177e68f8c7d9 and I'm fine with it, thanks. I will close this issue.

@jordanpadams, I've [filed a ticket in the template-repo-python](https://github.com/NASA-PDS/template-repo-python/issues/89) to address the better namespace package handling amongst other modernizations.
